-- VERIFICATION SCRIPT FOR HISTORICAL DSE DATA IMPORT

-- 1. Total historical records
SELECT COUNT(*) AS TOTAL_RECORDS FROM COMPANY_PRICE_HISTORY;

-- 2. Unique companies with historical data
SELECT COUNT(DISTINCT COMPANY_ID) AS UNIQUE_COMPANIES FROM COMPANY_PRICE_HISTORY;

-- 3 & 4. Date ranges
SELECT MIN(TRADING_DATE) AS EARLIEST_DATE, MAX(TRADING_DATE) AS LATEST_DATE FROM COMPANY_PRICE_HISTORY;

-- 5. Check for duplicates (COMPANY_ID + TRADING_DATE) - Should be 0
SELECT COMPANY_ID, TRADING_DATE, COUNT(*)
FROM COMPANY_PRICE_HISTORY
GROUP BY COMPANY_ID, TRADING_DATE
HAVING COUNT(*) > 1;

-- 6. Invalid OHLC relationships - Should be 0
SELECT COUNT(*)
FROM COMPANY_PRICE_HISTORY
WHERE HIGH_PRICE < LOW_PRICE 
   OR HIGH_PRICE < OPEN_PRICE 
   OR HIGH_PRICE < PRICE 
   OR LOW_PRICE > OPEN_PRICE 
   OR LOW_PRICE > PRICE;

-- 7. Negative values - Should be 0
SELECT COUNT(*)
FROM COMPANY_PRICE_HISTORY
WHERE OPEN_PRICE < 0 OR HIGH_PRICE < 0 OR LOW_PRICE < 0 OR PRICE < 0 OR VOLUME < 0;

-- 8. Zero-price observations - Should be 0
SELECT COUNT(*)
FROM COMPANY_PRICE_HISTORY
WHERE OPEN_PRICE = 0 AND HIGH_PRICE = 0 AND LOW_PRICE = 0 AND PRICE = 0;

-- 9. Imported source metadata check
SELECT SOURCE, SOURCE_DATASET, COUNT(*) 
FROM COMPANY_PRICE_HISTORY 
GROUP BY SOURCE, SOURCE_DATASET;

-- 13. Sample Company Verification (3 companies)
SELECT c.TICKER_SYMBOL,
       MIN(h.TRADING_DATE) AS FIRST_DATE,
       MAX(h.TRADING_DATE) AS LAST_DATE,
       COUNT(h.HISTORICAL_PRICE_ID) AS OBS_COUNT,
       MIN(h.PRICE) AS MIN_CLOSE,
       MAX(h.PRICE) AS MAX_CLOSE
FROM COMPANY_PRICE_HISTORY h
JOIN COMPANIES c ON h.COMPANY_ID = c.COMPANY_ID
GROUP BY c.TICKER_SYMBOL
FETCH FIRST 3 ROWS ONLY;
