CREATE TABLE sectors (
    sector_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sector_name  VARCHAR2(100) NOT NULL,
    description  VARCHAR2(255),

    CONSTRAINT pk_sectors
        PRIMARY KEY (sector_id),

    CONSTRAINT uq_sectors_name
        UNIQUE (sector_name)
);