CREATE TABLE companies (
    company_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_name    VARCHAR2(150) NOT NULL,
    ticker_symbol   VARCHAR2(20) NOT NULL,
    sector_id       NUMBER NOT NULL,
    current_price   NUMBER(14,2) NOT NULL,
    market_cap      NUMBER(20,2),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_companies
        PRIMARY KEY (company_id),

    CONSTRAINT uq_companies_ticker
        UNIQUE (ticker_symbol),

    CONSTRAINT ck_companies_price
        CHECK (current_price > 0),

    CONSTRAINT ck_companies_market_cap
        CHECK (market_cap IS NULL OR market_cap >= 0),

    CONSTRAINT fk_companies_sector
        FOREIGN KEY (sector_id)
        REFERENCES sectors (sector_id)
);