DROP TABLE portfolios CASCADE CONSTRAINTS;

CREATE TABLE portfolios (
    portfolio_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id         NUMBER NOT NULL,
    portfolio_name  VARCHAR2(100) NOT NULL,
    description     VARCHAR2(255),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_portfolios
        PRIMARY KEY (portfolio_id),

    CONSTRAINT uq_portfolios_user_name
        UNIQUE (user_id, portfolio_name),

    CONSTRAINT fk_portfolios_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (user_id)
);