CREATE TABLE watchlists (
    watchlist_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id         NUMBER NOT NULL,
    watchlist_name  VARCHAR2(100) NOT NULL,
    description     VARCHAR2(255),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_watchlists
        PRIMARY KEY (watchlist_id),

    CONSTRAINT uq_watchlists_user_name
        UNIQUE (user_id, watchlist_name),

    CONSTRAINT fk_watchlists_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (user_id)
);