CREATE TABLE transactions (
    transaction_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id      NUMBER NOT NULL,
    company_id        NUMBER NOT NULL,
    transaction_type  VARCHAR2(10) NOT NULL,
    quantity          NUMBER(14,4) NOT NULL,
    price_per_share   NUMBER(14,2) NOT NULL,
    transaction_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_transactions
        PRIMARY KEY (transaction_id),

    CONSTRAINT ck_transactions_type
        CHECK (transaction_type IN ('BUY', 'SELL')),

    CONSTRAINT ck_transactions_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_transactions_price
        CHECK (price_per_share > 0),

    CONSTRAINT fk_transactions_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolios (portfolio_id),

    CONSTRAINT fk_transactions_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
);