CREATE TABLE dividends (
    dividend_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id          NUMBER NOT NULL,
    dividend_per_share  NUMBER(14,2) NOT NULL,
    declaration_date    DATE NOT NULL,
    payment_date        DATE NOT NULL,

    CONSTRAINT pk_dividends
        PRIMARY KEY (dividend_id),

    CONSTRAINT ck_dividends_amount
        CHECK (dividend_per_share > 0),

    CONSTRAINT ck_dividends_dates
        CHECK (payment_date >= declaration_date),

    CONSTRAINT fk_dividends_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
);