CREATE TABLE transaction_audit (
    audit_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transaction_id NUMBER NOT NULL,
    action_type    VARCHAR2(10) NOT NULL,
    action_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by     VARCHAR2(100),
    details        VARCHAR2(1000),

    CONSTRAINT pk_transaction_audit
        PRIMARY KEY (audit_id),

    CONSTRAINT ck_transaction_audit_action
        CHECK (action_type IN ('INSERT', 'UPDATE', 'DELETE')),

    CONSTRAINT fk_transaction_audit_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transactions (transaction_id)
);