CREATE TABLE portfolio_snapshots (
    snapshot_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id   NUMBER NOT NULL,
    snapshot_date  DATE NOT NULL,
    total_value    NUMBER(20,2) NOT NULL,

    CONSTRAINT pk_portfolio_snapshots
        PRIMARY KEY (snapshot_id),

    CONSTRAINT uq_portfolio_snapshot_date
        UNIQUE (portfolio_id, snapshot_date),

    CONSTRAINT ck_portfolio_snapshot_value
        CHECK (total_value >= 0),

    CONSTRAINT fk_portfolio_snapshots_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolios (portfolio_id)
);