-- ============================================================
-- ShareSync - Database Schema: Company Price History
-- File: 12_company_price_history.sql
-- Table: COMPANY_PRICE_HISTORY
-- Description: Stores time-series market price snapshots per company.
-- ============================================================

CREATE TABLE company_price_history (
    price_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id       NUMBER NOT NULL,
    price            NUMBER(14, 2) NOT NULL,
    open_price       NUMBER(14, 2),
    high_price       NUMBER(14, 2),
    low_price        NUMBER(14, 2),
    volume           NUMBER(18, 0),
    recorded_at      TIMESTAMP NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_company_price_history PRIMARY KEY (price_history_id),
    CONSTRAINT fk_price_history_company FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT ck_price_hist_price CHECK (price > 0),
    CONSTRAINT ck_price_hist_open CHECK (open_price IS NULL OR open_price > 0),
    CONSTRAINT ck_price_hist_high CHECK (high_price IS NULL OR high_price > 0),
    CONSTRAINT ck_price_hist_low CHECK (low_price IS NULL OR low_price > 0),
    CONSTRAINT ck_price_hist_volume CHECK (volume IS NULL OR volume >= 0)
);

CREATE INDEX idx_price_hist_comp_date ON company_price_history (company_id, recorded_at);
