-- ============================================================
-- ShareSync - Database Schema: Price and Portfolio Alerts
-- File: 13_alerts.sql
-- Table: ALERTS
-- Description: Stores user-configured market price and portfolio threshold alerts.
-- ============================================================

CREATE TABLE alerts (
    alert_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id          NUMBER NOT NULL,
    company_id       NUMBER,
    portfolio_id     NUMBER,
    alert_type       VARCHAR2(30) NOT NULL,
    threshold_value  NUMBER(14, 2) NOT NULL,
    is_active        NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    triggered_at     TIMESTAMP,
    message          VARCHAR2(500),
    CONSTRAINT pk_alerts PRIMARY KEY (alert_id),
    CONSTRAINT fk_alerts_user FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_alerts_company FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_alerts_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (portfolio_id) ON DELETE CASCADE,
    CONSTRAINT ck_alerts_type CHECK (alert_type IN ('PRICE_ABOVE', 'PRICE_BELOW', 'PORTFOLIO_VALUE_ABOVE', 'PORTFOLIO_VALUE_BELOW')),
    CONSTRAINT ck_alerts_threshold CHECK (threshold_value > 0),
    CONSTRAINT ck_alerts_is_active CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_alerts_target CHECK (
        (alert_type IN ('PRICE_ABOVE', 'PRICE_BELOW') AND company_id IS NOT NULL) OR
        (alert_type IN ('PORTFOLIO_VALUE_ABOVE', 'PORTFOLIO_VALUE_BELOW') AND portfolio_id IS NOT NULL)
    )
);

CREATE INDEX idx_alerts_user ON alerts (user_id, is_active);
CREATE INDEX idx_alerts_price_eval ON alerts (is_active, company_id, alert_type);
CREATE INDEX idx_alerts_port_eval ON alerts (is_active, portfolio_id, alert_type);
