-- ============================================================
-- ShareSync - Database Schema: Notifications Center
-- File: 15_notifications.sql
-- Table: NOTIFICATIONS
-- Description: In-app notification center storing price/portfolio alerts,
--              dividend announcements, system updates, and market sync events.
-- ============================================================

CREATE TABLE notifications (
    notification_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id               NUMBER NOT NULL,
    notification_type     VARCHAR2(30) NOT NULL,
    title                 VARCHAR2(150) NOT NULL,
    message               VARCHAR2(1000) NOT NULL,
    is_read               NUMBER(1) DEFAULT 0 NOT NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    related_entity_type   VARCHAR2(50),
    related_entity_id     NUMBER,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_notifications_is_read CHECK (is_read IN (0, 1))
);

CREATE INDEX idx_notifications_user ON notifications (user_id, is_read, created_at DESC);
CREATE INDEX idx_notifications_entity ON notifications (user_id, related_entity_type, related_entity_id);
