-- ============================================================
-- ShareSync - Database Schema: Portfolio Goals
-- File: 16_portfolio_goals.sql
-- Table: PORTFOLIO_GOALS
-- Description: Financial goals associated with portfolios (Target Valuation, Target Return, Target Dividend Income).
-- ============================================================

CREATE TABLE portfolio_goals (
    goal_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id          NUMBER NOT NULL,
    portfolio_id     NUMBER NOT NULL,
    goal_type        VARCHAR2(40) NOT NULL,
    target_value     NUMBER(15, 2) NOT NULL,
    target_date      DATE,
    title            VARCHAR2(150) NOT NULL,
    description      VARCHAR2(500),
    is_active        NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    CONSTRAINT pk_portfolio_goals PRIMARY KEY (goal_id),
    CONSTRAINT fk_portfolio_goals_user FOREIGN KEY (user_id) REFERENCES app_users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_goals_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios (portfolio_id) ON DELETE CASCADE,
    CONSTRAINT ck_portfolio_goals_type CHECK (goal_type IN ('TARGET_PORTFOLIO_VALUE', 'TARGET_RETURN', 'TARGET_DIVIDEND_INCOME')),
    CONSTRAINT ck_portfolio_goals_target CHECK (target_value > 0),
    CONSTRAINT ck_portfolio_goals_active CHECK (is_active IN (0, 1))
);

CREATE INDEX idx_portfolio_goals_user ON portfolio_goals (user_id, is_active, created_at DESC);
CREATE INDEX idx_portfolio_goals_portfolio ON portfolio_goals (portfolio_id, is_active);
